[package]
name = "rust-gurobi-examples"
version = "0.1.0"
authors = ["Yusuke Sasaki <y_sasaki@nuem.nagoya-u.ac.jp>"]

[dependencies]
ndarray = "*"
itertools = "*"

[dependencies.gurobi]
git = "https://github.com/ys-nuem/rust-gurobi.git"
branch = "master"